FROM postgres:15-alpine

# Set default environment variables
ENV POSTGRES_DB=htf_sunup_production
ENV POSTGRES_USER=htf_sunup_user

# Expose the PostgreSQL port
EXPOSE 5432

# Use the default postgres entrypoint
CMD ["postgres"]