version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: template_postgres
    environment:
      POSTGRES_DB: template_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    container_name: template_backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/template_db
      PORT: 3001
      FRONTEND_URL: http://localhost:3000
    ports:
      - '3001:3001'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./apps/backend/src:/app/apps/backend/src
      - ./apps/backend/drizzle.config.ts:/app/apps/backend/drizzle.config.ts

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    container_name: template_frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./apps/frontend/src:/app/apps/frontend/src

volumes:
  postgres_data:
