version: '1'
previews:
  generation: automatic
  expireAfterDays: 1
services:
  - type: web
    name: htf-sunup-backend
    runtime: node
    repo: https://github.com/tfoutrein/htf-sunup
    plan: starter
    envVars:
      - key: FACEBOOK_CALLBACK_URL
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: S3_BUCKET_NAME
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_REGION
        sync: false
      - key: S3_ENDPOINT
        sync: false
      - key: PASSWORD_SALT_ROUNDS
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: htf-sunup-postgres
          property: connectionString
      - key: PORT
        sync: false
      - key: NODE_ENV
        sync: false
    region: oregon
    buildCommand: cd apps/backend && pnpm install && pnpm build
    startCommand: cd apps/backend && pnpm start:prod
    healthCheckPath: /api/health
    autoDeployTrigger: commit
    initialDeployHook: cd apps/backend && pnpm preview:copy-prod:prod

databases:
  - name: htf-sunup-postgres
    databaseName: htf_sunup_postgres
    user: htf_sunup_postgres_user
    plan: basic-256mb
    previewPlan: basic-256mb
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: '16'
    diskSizeGB: 1
