services:
  # PostgreSQL Database
  - type: pserv
    name: htf-sunup-postgres
    plan: free

  # Backend API
  - type: web
    name: htf-sunup-backend
    runtime: node
    plan: free
    buildCommand: cd apps/backend && pnpm install && pnpm build
    startCommand: cd apps/backend && pnpm start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: htf-sunup-postgres
          property: connectionString
      - key: FRONTEND_URL
        value: https://htf-sunup-khbf39e25-thomasfoutreins-projects.vercel.app
      - key: CORS_ORIGIN
        value: https://htf-sunup-khbf39e25-thomasfoutreins-projects.vercel.app
    healthCheckPath: /health
