services:
  # Backend API
  - type: web
    name: htf-sunup-backend
    runtime: node
    plan: free
    buildCommand: cd apps/backend && pnpm install && pnpm build
    startCommand: cd apps/backend && pnpm start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://htf-sunup-frontend.vercel.app
      - key: CORS_ORIGIN
        value: https://htf-sunup-frontend.vercel.app
      - key: JWT_SECRET
        generateValue: true
      - key: PASSWORD_SALT_ROUNDS
        value: '12'
      - key: DATABASE_URL
        fromDatabase:
          name: htf-sunup-postgres
          property: connectionString
      - key: S3_ENDPOINT
        value: https://b2y8.par5.idrivee2-11.com
      - key: S3_REGION
        value: eu-west-1
      - key: S3_ACCESS_KEY_ID
        value: PBL16uf72p6Ohufxizs5
      - key: S3_SECRET_ACCESS_KEY
        value: CZ4kHYSS2HWIyKMf0VvRXDmJPdYAl47QJf4tGkze
      - key: S3_BUCKET_NAME
        value: htf-sunup-storage
    healthCheckPath: /health

databases:
  - name: htf-sunup-postgres
    plan: free
    databaseName: htf_sunup_production
    user: htf_sunup_user
